tas_car:
  # Publish all joint states -----------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Wheel Controllers      -------------------------------
  wheel_rb_controller:
    type: effort_controllers/JointEffortController
    joint: base_r_b_wheel_joint
    pid: {p: 30.0, i: 0.5, d: 1.3}
  
  wheel_lb_controller:
    type: effort_controllers/JointEffortController
    joint: base_l_b_wheel_joint
    pid: {p: 30.0, i: 0.5, d: 1.3}
